#!/bin/bash


sets="ar3.arff ar4.arff ar5.arff cm1.arff kc1.arff kc2.arff kc3.arff mw1.arff pc1.arff pc2.arff pc3.arff pc4.arff mc2.arff jm1.arff"

for file in $sets
do
    /opt/local/bin/python2.6 idea_img.py --train arff/defect/$file --accept 0.5 --stratified 5
    echo ""
done
