#!/bin/bash


sets="cm1.arff kc1.arff kc2.arff kc3.arff mw1.arff pc1.arff"
jm1="jm1.arff"
cm1="cm1.arff"
kc1="kc1.arff"
kc2="kc2.arff"
kc3="kc3.arff"
mc2="mc2.arff"

for file in $sets
do
#    echo "Running arff/defect/$file"
    /usr/bin/env python cliffav.py --train ../python/arff/defect/$file
#    grep Perform $file.csv > $file.perform.csv;
#    grep __init__ $file.csv > $file.quadrants.csv
done
