#!/bin/bash

accepts="0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5"

for ACCEPTANCE in $accepts
do
    echo "ACCEPTANCE: $ACCEPTANCE"
    for FILE in arff/defect/*.arff
    do
	echo "DATASET: $FILE"
	./idea.py --cluster --equalfrequency --logX --logY --m 1 --n 1 --train $FILE --stratified 4 1 --q 20 --acceptance $ACCEPTANCE --output $ACCEPTANCE
    done
done