#!/bin/bash

# Run Effort Sets
echo "********** RUNNING EFFORT SETS **********"
for FILENAME in arff/*.arff;
do
    echo $FILENAME
    echo "5 fold"
    echo "K = 1"
    ./baseline.py --xval 5 --data $FILENAME --k 1
    echo "K = 5"
    ./baseline.py --xval 5 --data $FILENAME --k 5
    echo "K = 10"
    ./baseline.py --xval 5 --data $FILENAME --k 10
    echo ""
    echo "3  fold"
    echo "K = 1"
    ./baseline.py --xval 5 --data $FILENAME --k 1
    echo "K = 5"
    ./baseline.py --xval 5 --data $FILENAME --k 5
    echo "K = 10"
    ./baseline.py --xval 5 --data $FILENAME --k 10
    echo ""
done



echo "********** Leave One Out   ***********"
for FILENAME in arff/*.arff;
do 
	echo $FILENAME
	./baseline.py --loo --data $FILENAME --k 5
done


# Run Defect Sets
echo "********** RUNNING DEFECT SETS **********"
#for FILENAME in arff/defect/*.arff;
#do
#    echo $FILENAME
#    time ./idea.py --cluster --train $FILENAME --equalfrequency --logX --m 1 --n 1 --q 20
#done
