#!/bin/bash

# Run Effort Sets
echo "********** RUNNING EFFORT SETS **********"
echo "********** 5 fold Cross Val    **********"
for FILENAME in arff/*.arff;
do
    echo $FILENAME
    ./baseline.py --xval 5 --data $FILENAME
done

echo "********** Leave One Out   ***********"
for FILENAME in arff/*.arff;
do 
	echo $FILENAME
	./baseline.py -loo --data $FILENAME
done


# Run Defect Sets
echo "********** RUNNING DEFECT SETS **********"
#for FILENAME in arff/defect/*.arff;
#do
#    echo $FILENAME
#    time ./idea.py --cluster --train $FILENAME --equalfrequency --logX --m 1 --n 1 --q 20
#done
