(defun distance (this that)
  "Distance between two discrete lists"
  (let ((d 0))
    (dolist (one this)
      (if (eql one (nth (position one this) that))
	  (incf d)))
    d))

(defun ndistance (this that)
  (let ((d 0))
    (dolist (one this)
      (dolist (two that)
	(if (and (numberp one) (numberp two))
	    (setf d (+ d (expt (- two one) 2)))
	    (if (eql one two)
		(incf d)))))
    (sqrt d)))
