(defun normalize (these)
  (let (normalized)
    (dolist (column (transpose these))
      (let ((n (make-normal-from-list column)))
	(push (reverse (mapcar #'(lambda (x)
				   (/ (- x (normal-min n))
				      (- (normal-max n) (normal-min n))))
			       column)) normalized)))
    (transpose normalized)))