(defun normalize (these)
  (let* ((normalized)
	 (columns (transpose these))
	 (klass (first (last columns)))
	 (columns (remove klass (copy-list columns))))
    (dolist (column columns)
      (let ((n (make-normal-from-list column)))
	(push (reverse (mapcar #'(lambda (x)
				   (/ (1+ (- x (normal-min n)))
				      (1+ (- (normal-max n) (normal-min n)))))
			       column)) normalized)))
    (push klass normalized)
    (mapcar #'reverse (transpose normalized))))