(defun gas-pockets (ctree &optional (magic-number 500))
  (if (and (and (null (node-right ctree)) (null (node-left ctree)))
	   (> 2 (length (node-contents ctree)))
	   (> (node-variance ctree) magic-number))
      (let ((separated (separate (node-contents ctree))))
	(setf (node-right ctree)
	      (make-node :contents (first separated)
			 :variance (variance (first separated))))
	(setf (node-left ctree)
	      (make-node :contents (second separated)
			 :variance (variance (first separated))))))
  (unless (null (node-right ctree)) 
    (gas-pockets (node-right ctree)))
  (unless (null (node-left ctree))
    (gas-pockets (node-left ctree)))
  ctree)
      