(defun majority-class (l)	  
  (let ((ht (make-hash-table))
	(highest 0)
	(majority nil))
    (dolist (v l)
      (if (null (gethash v ht))
	  (setf (gethash v ht) 1)
	  (incf (gethash v ht))))
    (dohash (key value ht)
      (if (> value highest)
	  (progn 
	    (setf highest value)
	    (setf majority key))))
    majority))
