#!/bin/bash


sets="kc1.arff kc2.arff kc3.arff mw1.arff pc1.arff"

for file in $sets
do
    echo "Running ../python/arff/defect/$file"
    /opt/local/bin/python2.6 idea.py --train ../python/arff/defect/$file --xval 5 > $file.csv
done